// Edital verticalizado do concurso PRF 2021 (Estratégia Concursos)
// Estrutura: Blocos > Disciplinas > Tópicos hierárquicos (numero/titulo/nivel)

export type TopicoSeed = {
  numero: string;
  titulo: string;
  nivel: number; // 1, 2 ou 3 (profundidade)
};

export type DisciplinaSeed = {
  bloco: "I" | "II" | "III";
  nome: string;
  ordem: number;
  topicos: TopicoSeed[];
};

export const EDITAL_PRF: DisciplinaSeed[] = [
  {
    bloco: "I",
    nome: "Língua Portuguesa",
    ordem: 1,
    topicos: [
      { numero: "1", titulo: "Compreensão e interpretação de textos de gêneros variados.", nivel: 1 },
      { numero: "2", titulo: "Reconhecimento de tipos e gêneros textuais.", nivel: 1 },
      { numero: "3", titulo: "Domínio da ortografia oficial.", nivel: 1 },
      { numero: "4", titulo: "Domínio dos mecanismos de coesão textual.", nivel: 1 },
      { numero: "4.1", titulo: "Emprego de elementos de referenciação, substituição e repetição, de conectores e de outros elementos de sequenciação textual.", nivel: 2 },
      { numero: "4.2", titulo: "Emprego de tempos e modos verbais.", nivel: 2 },
      { numero: "5", titulo: "Domínio da estrutura morfossintática do período.", nivel: 1 },
      { numero: "5.1", titulo: "Emprego das classes de palavras.", nivel: 2 },
      { numero: "5.2", titulo: "Relações de coordenação entre orações e entre termos da oração.", nivel: 2 },
      { numero: "5.3", titulo: "Relações de subordinação entre orações e entre termos da oração.", nivel: 2 },
      { numero: "5.4", titulo: "Emprego dos sinais de pontuação.", nivel: 2 },
      { numero: "5.5", titulo: "Concordância verbal e nominal.", nivel: 2 },
      { numero: "5.6", titulo: "Regência verbal e nominal.", nivel: 2 },
      { numero: "5.7", titulo: "Emprego do sinal indicativo de crase.", nivel: 2 },
      { numero: "5.8", titulo: "Colocação dos pronomes átonos.", nivel: 2 },
      { numero: "6", titulo: "Reescrita de frases e parágrafos do texto.", nivel: 1 },
      { numero: "6.1", titulo: "Significação das palavras.", nivel: 2 },
      { numero: "6.2", titulo: "Substituição de palavras ou de trechos de texto.", nivel: 2 },
      { numero: "6.3", titulo: "Reorganização da estrutura de orações e de períodos do texto.", nivel: 2 },
      { numero: "6.4", titulo: "Reescrita de textos de diferentes gêneros e níveis de formalidade.", nivel: 2 },
      { numero: "7", titulo: "Correspondência oficial (conforme Manual de Redação da Presidência da República).", nivel: 1 },
      { numero: "7.1", titulo: "Aspectos gerais da redação oficial.", nivel: 2 },
      { numero: "7.2", titulo: "Finalidade dos expedientes oficiais.", nivel: 2 },
      { numero: "7.3", titulo: "Adequação da linguagem ao tipo de documento.", nivel: 2 },
      { numero: "7.4", titulo: "Adequação do formato do texto ao gênero.", nivel: 2 },
    ],
  },
  {
    bloco: "I",
    nome: "Raciocínio Lógico-Matemático",
    ordem: 2,
    topicos: [
      { numero: "1", titulo: "Modelagem de situações-problema por meio de equações do 1º e 2º graus e sistemas lineares.", nivel: 1 },
      { numero: "2", titulo: "Noção de função.", nivel: 1 },
      { numero: "2.1", titulo: "Análise gráfica.", nivel: 2 },
      { numero: "2.2", titulo: "Funções afim, quadrática, exponencial e logarítmica.", nivel: 2 },
      { numero: "2.3", titulo: "Aplicações.", nivel: 2 },
      { numero: "3", titulo: "Taxas de variação de grandezas.", nivel: 1 },
      { numero: "3.1", titulo: "Razão e proporção com aplicações.", nivel: 2 },
      { numero: "3.2", titulo: "Regra de três simples e composta.", nivel: 2 },
      { numero: "4", titulo: "Porcentagem.", nivel: 1 },
      { numero: "5", titulo: "Regularidades e padrões em sequências.", nivel: 1 },
      { numero: "5.1", titulo: "Sequências numéricas.", nivel: 2 },
      { numero: "5.2", titulo: "Progressão aritmética e progressão geométrica.", nivel: 2 },
      { numero: "6", titulo: "Noções básicas de contagem, probabilidade e estatística.", nivel: 1 },
      { numero: "7", titulo: "Descrição e análise de dados.", nivel: 1 },
      { numero: "7.1", titulo: "Leitura e interpretação de tabelas e gráficos apresentados em diferentes linguagens e representações.", nivel: 2 },
      { numero: "7.2", titulo: "Cálculo de médias e análise de desvios de conjuntos de dados.", nivel: 2 },
      { numero: "8", titulo: "Noções básicas de teoria dos conjuntos.", nivel: 1 },
      { numero: "9", titulo: "Análise e interpretação de diferentes representações de figuras planas, como desenhos, mapas e plantas.", nivel: 1 },
      { numero: "9.1", titulo: "Utilização de escalas.", nivel: 2 },
      { numero: "9.2", titulo: "Visualização de figuras espaciais em diferentes posições.", nivel: 2 },
      { numero: "9.3", titulo: "Representações bidimensionais de projeções, planificações e cortes.", nivel: 2 },
      { numero: "10", titulo: "Métrica.", nivel: 1 },
      { numero: "10.1", titulo: "Áreas e volumes.", nivel: 2 },
      { numero: "10.2", titulo: "Estimativas.", nivel: 2 },
      { numero: "10.3", titulo: "Aplicações.", nivel: 2 },
    ],
  },
  {
    bloco: "I",
    nome: "Informática",
    ordem: 3,
    topicos: [
      { numero: "1", titulo: "Conceito de internet e intranet.", nivel: 1 },
      { numero: "2", titulo: "Conceitos e modos de utilização de tecnologias, ferramentas, aplicativos e procedimentos associados à internet/intranet.", nivel: 1 },
      { numero: "2.1", titulo: "Ferramentas e aplicativos comerciais de navegação, de correio eletrônico, de grupos de discussão, de busca, de pesquisa, de redes sociais e ferramentas colaborativas.", nivel: 2 },
      { numero: "2.2", titulo: "Noções de sistema operacional (ambiente Windows).", nivel: 2 },
      { numero: "2.3", titulo: "Acesso a distância a computadores, transferência de informação e arquivos, aplicativos de áudio, vídeo e multimídia.", nivel: 2 },
      { numero: "3", titulo: "Transformação digital.", nivel: 1 },
      { numero: "3.1", titulo: "Internet das coisas (IoT).", nivel: 2 },
      { numero: "3.2", titulo: "Big data.", nivel: 2 },
      { numero: "3.3", titulo: "Inteligência artificial.", nivel: 2 },
      { numero: "4", titulo: "Conceitos de proteção e segurança.", nivel: 1 },
      { numero: "4.1", titulo: "Noções de vírus, worms, phishing e pragas virtuais.", nivel: 2 },
      { numero: "4.2", titulo: "Aplicativos para segurança (antivírus, firewall, anti-spyware, VPN, etc.).", nivel: 2 },
      { numero: "5", titulo: "Computação na nuvem (cloud computing).", nivel: 1 },
    ],
  },
  {
    bloco: "I",
    nome: "Física",
    ordem: 4,
    topicos: [
      { numero: "1", titulo: "Cinemática escalar, cinemática vetorial.", nivel: 1 },
      { numero: "2", titulo: "Movimento circular.", nivel: 1 },
      { numero: "3", titulo: "Leis de Newton e suas aplicações.", nivel: 1 },
      { numero: "4", titulo: "Trabalho.", nivel: 1 },
      { numero: "5", titulo: "Potência.", nivel: 1 },
      { numero: "6", titulo: "Energia cinética, energia potencial, atrito.", nivel: 1 },
      { numero: "7", titulo: "Conservação de energia e suas transformações.", nivel: 1 },
      { numero: "8", titulo: "Quantidade de movimento e conservação da quantidade de movimento, impulso.", nivel: 1 },
      { numero: "9", titulo: "Colisões.", nivel: 1 },
    ],
  },
  {
    bloco: "I",
    nome: "Ética e Cidadania",
    ordem: 5,
    topicos: [
      { numero: "1", titulo: "Ética e moral.", nivel: 1 },
      { numero: "2", titulo: "Ética, princípios e valores.", nivel: 1 },
      { numero: "3", titulo: "Ética e função pública: integridade.", nivel: 1 },
      { numero: "4", titulo: "Ética no setor público.", nivel: 1 },
      { numero: "4.1", titulo: "Princípios da Administração Pública: moralidade (art. 37 da CF).", nivel: 2 },
      { numero: "4.2", titulo: "Deveres dos servidores públicos: moralidade administrativa (Lei nº 8.112/1990, art. 116, IX).", nivel: 2 },
      { numero: "4.3", titulo: "Política de governança da administração pública federal (Decreto nº 9.203/2017).", nivel: 2 },
      { numero: "4.4", titulo: "Promoção da ética e regras de conduta para servidores.", nivel: 2 },
      { numero: "4.4.1", titulo: "Código de Ética Profissional do Servidor Público Civil do Poder Executivo Federal (Decreto nº 1.171/1994).", nivel: 3 },
      { numero: "4.4.2", titulo: "Sistema de Gestão da Ética do Poder Executivo Federal e Comissões de Ética (Decreto nº 6.029/2007).", nivel: 3 },
      { numero: "4.4.3", titulo: "Código de Conduta da Alta Administração Federal (Exposição de Motivos nº 37/2000).", nivel: 3 },
      { numero: "5", titulo: "Ética e democracia: exercício da cidadania.", nivel: 1 },
      { numero: "5.1", titulo: "Promoção da transparência ativa e do acesso à informação (Lei nº 12.527/2011 e Decreto nº 7.724/2012).", nivel: 2 },
      { numero: "5.2", titulo: "Tratamento de conflitos de interesses e nepotismo (Lei nº 12.813/2013 e Decreto nº 7.203/2010).", nivel: 2 },
    ],
  },
  {
    bloco: "I",
    nome: "Geopolítica",
    ordem: 6,
    topicos: [
      { numero: "1", titulo: "O Brasil político: nação e território.", nivel: 1 },
      { numero: "2", titulo: "Organização do Estado Brasileiro.", nivel: 1 },
      { numero: "3", titulo: "A divisão interregional do trabalho e da produção no Brasil.", nivel: 1 },
      { numero: "4", titulo: "A estrutura urbana brasileira e as grandes metrópoles.", nivel: 1 },
      { numero: "5", titulo: "Distribuição espacial da população no Brasil e movimentos migratórios internos.", nivel: 1 },
      { numero: "6", titulo: "Integração entre indústria e estrutura urbana e setor agrícola no Brasil.", nivel: 1 },
      { numero: "7", titulo: "Rede de transporte no Brasil: modais e principais infraestruturas.", nivel: 1 },
      { numero: "8", titulo: "A integração do Brasil ao processo de internacionalização da economia.", nivel: 1 },
      { numero: "9", titulo: "Geografia e gestão ambiental.", nivel: 1 },
      { numero: "10", titulo: "Macrodivisão natural do espaço brasileiro: biomas, domínios e ecossistemas.", nivel: 1 },
    ],
  },
  {
    bloco: "I",
    nome: "Língua Estrangeira (Inglês ou Espanhol)",
    ordem: 7,
    topicos: [
      { numero: "1 (Inglês)", titulo: "Compreensão de texto escrito em língua inglesa.", nivel: 1 },
      { numero: "2 (Inglês)", titulo: "Itens gramaticais relevantes para a compreensão dos conteúdos semânticos.", nivel: 1 },
      { numero: "1 (Espanhol)", titulo: "Compreensão de texto escrito em língua espanhola.", nivel: 1 },
      { numero: "2 (Espanhol)", titulo: "Itens gramaticais relevantes para a compreensão dos conteúdos semânticos.", nivel: 1 },
    ],
  },
  {
    bloco: "II",
    nome: "Legislação de Trânsito",
    ordem: 8,
    topicos: [
      { numero: "1", titulo: "Lei nº 9.503/1997 (Código de Trânsito Brasileiro) e suas alterações, inclusive as da Lei nº 14.071/2020.", nivel: 1 },
      { numero: "2", titulo: "Lei nº 5.970/1973.", nivel: 1 },
      { numero: "3", titulo: "Resoluções do Conselho Nacional de Trânsito (CONTRAN) e suas alterações.", nivel: 1 },
      { numero: "3.1", titulo: "Res. 04/1998, 14/1998, 24/1998, 36/1998, 92/1998 (exceto anexos), 110/2000, 160/2004.", nivel: 2 },
      { numero: "3.2", titulo: "Res. 210/2011, 211/2006, 216/2006, 227/2007 (exceto anexos), 253/2007, 254/2007, 268/2008.", nivel: 2 },
      { numero: "3.3", titulo: "Res. 290/2008, 292/2008, 349/2010, 360/2010, 432/2013, 441/2013, 453/2013, 471/2013.", nivel: 2 },
      { numero: "3.4", titulo: "Res. 508/2014, 520/2015, 525/2015, 552/2015 (exceto anexos), 561/2015 (exceto fichas), 619/2016.", nivel: 2 },
      { numero: "3.5", titulo: "Res. 667/2017 (exceto anexos), 723/2018, 735/2018 (exceto anexos), 740/2018, 780/2019.", nivel: 2 },
      { numero: "3.6", titulo: "Res. 789/2020 (Anexo I), 798/2020, 803/2020, 806/2020, 809/2020, 810/2020.", nivel: 2 },
    ],
  },
  {
    bloco: "III",
    nome: "Direito Administrativo",
    ordem: 9,
    topicos: [
      { numero: "1", titulo: "Noções de organização administrativa.", nivel: 1 },
      { numero: "1.1", titulo: "Centralização, descentralização, concentração e desconcentração.", nivel: 2 },
      { numero: "1.2", titulo: "Administração direta e indireta.", nivel: 2 },
      { numero: "1.3", titulo: "Autarquias, fundações, empresas públicas e sociedades de economia mista.", nivel: 2 },
      { numero: "2", titulo: "Ato administrativo.", nivel: 1 },
      { numero: "2.1", titulo: "Conceito, requisitos, atributos, classificação e espécies.", nivel: 2 },
      { numero: "3", titulo: "Agentes públicos.", nivel: 1 },
      { numero: "3.1", titulo: "Legislação pertinente.", nivel: 2 },
      { numero: "3.1.1", titulo: "Lei nº 8.112/1990 e suas alterações.", nivel: 3 },
      { numero: "3.1.2", titulo: "Disposições constitucionais aplicáveis.", nivel: 3 },
      { numero: "3.2", titulo: "Disposições doutrinárias.", nivel: 2 },
      { numero: "3.2.1", titulo: "Conceito.", nivel: 3 },
      { numero: "3.2.2", titulo: "Espécies.", nivel: 3 },
      { numero: "3.2.3", titulo: "Cargo, emprego e função pública.", nivel: 3 },
      { numero: "3.3", titulo: "Carreira de policial rodoviário federal.", nivel: 2 },
      { numero: "3.3.1", titulo: "Lei nº 9.654/1998 e suas alterações (carreira de PRF).", nivel: 3 },
      { numero: "3.3.2", titulo: "Lei nº 12.855/2013 (indenização fronteiras).", nivel: 3 },
      { numero: "3.3.3", titulo: "Lei nº 13.712/2018 (indenização PRF).", nivel: 3 },
      { numero: "3.3.4", titulo: "Decreto nº 8.282/2014 (carreira de PRF).", nivel: 3 },
      { numero: "4", titulo: "Poderes administrativos.", nivel: 1 },
      { numero: "4.1", titulo: "Hierárquico, disciplinar, regulamentar e de polícia.", nivel: 2 },
      { numero: "4.2", titulo: "Uso e abuso do poder.", nivel: 2 },
      { numero: "5", titulo: "Licitação.", nivel: 1 },
      { numero: "5.1", titulo: "Princípios.", nivel: 2 },
      { numero: "5.2", titulo: "Contratação direta: dispensa e inexigibilidade.", nivel: 2 },
      { numero: "5.3", titulo: "Modalidades.", nivel: 2 },
      { numero: "5.4", titulo: "Tipos.", nivel: 2 },
      { numero: "5.5", titulo: "Procedimento.", nivel: 2 },
      { numero: "6", titulo: "Controle da Administração Pública.", nivel: 1 },
      { numero: "6.1", titulo: "Controle exercido pela Administração Pública.", nivel: 2 },
      { numero: "6.2", titulo: "Controle judicial.", nivel: 2 },
      { numero: "6.3", titulo: "Controle legislativo.", nivel: 2 },
      { numero: "7", titulo: "Responsabilidade civil do Estado.", nivel: 1 },
      { numero: "7.1", titulo: "Responsabilidade civil do Estado no direito brasileiro.", nivel: 2 },
      { numero: "7.1.1", titulo: "Responsabilidade por ato comissivo do Estado.", nivel: 3 },
      { numero: "7.1.2", titulo: "Responsabilidade por omissão do Estado.", nivel: 3 },
      { numero: "7.2", titulo: "Requisitos para a demonstração da responsabilidade do Estado.", nivel: 2 },
      { numero: "7.3", titulo: "Causas excludentes e atenuantes da responsabilidade do Estado.", nivel: 2 },
      { numero: "8", titulo: "Regime jurídico-administrativo.", nivel: 1 },
      { numero: "8.1", titulo: "Conceito.", nivel: 2 },
      { numero: "8.2", titulo: "Princípios expressos e implícitos da Administração Pública.", nivel: 2 },
    ],
  },
  {
    bloco: "III",
    nome: "Direito Constitucional",
    ordem: 10,
    topicos: [
      { numero: "1", titulo: "Poder constituinte.", nivel: 1 },
      { numero: "1.1", titulo: "Fundamentos do poder constituinte.", nivel: 2 },
      { numero: "1.2", titulo: "Poder constituinte originário e derivado.", nivel: 2 },
      { numero: "1.3", titulo: "Reforma e revisão constitucionais.", nivel: 2 },
      { numero: "1.4", titulo: "Limitação do poder de revisão.", nivel: 2 },
      { numero: "1.5", titulo: "Emendas à Constituição.", nivel: 2 },
      { numero: "2", titulo: "Fundamentos constitucionais dos direitos e deveres fundamentais.", nivel: 1 },
      { numero: "2.1", titulo: "Direitos e deveres individuais e coletivos.", nivel: 2 },
      { numero: "2.2", titulo: "Direito à vida, à liberdade, à igualdade, à segurança e à propriedade.", nivel: 2 },
      { numero: "2.3", titulo: "Direitos sociais, nacionalidade, cidadania e direitos políticos.", nivel: 2 },
      { numero: "2.4", titulo: "Garantias constitucionais individuais.", nivel: 2 },
      { numero: "2.5", titulo: "Garantias dos direitos coletivos, sociais e políticos.", nivel: 2 },
      { numero: "2.6", titulo: "Remédios constitucionais.", nivel: 2 },
      { numero: "3", titulo: "Poder Executivo.", nivel: 1 },
      { numero: "3.1", titulo: "Forma e sistema de governo.", nivel: 2 },
      { numero: "3.2", titulo: "Chefia de Estado e chefia de governo.", nivel: 2 },
      { numero: "3.3", titulo: "Atribuições e responsabilidades do presidente da República.", nivel: 2 },
      { numero: "3.4", titulo: "Da União: bens e competências (arts. 20 a 24 da CF).", nivel: 2 },
      { numero: "4", titulo: "Defesa do Estado e das instituições democráticas.", nivel: 1 },
      { numero: "4.1", titulo: "Forças Armadas (art. 142, CF).", nivel: 2 },
      { numero: "4.2", titulo: "Segurança pública (art. 144 da CF).", nivel: 2 },
      { numero: "4.3", titulo: "Organização da segurança pública.", nivel: 2 },
      { numero: "4.4", titulo: "Atribuições constitucionais da Polícia Rodoviária Federal.", nivel: 2 },
      { numero: "5", titulo: "Ordem social.", nivel: 1 },
      { numero: "5.1", titulo: "Base e objetivos da ordem social.", nivel: 2 },
      { numero: "5.2", titulo: "Seguridade social.", nivel: 2 },
      { numero: "5.3", titulo: "Meio ambiente.", nivel: 2 },
      { numero: "5.4", titulo: "Família, criança, adolescente, idoso, índio.", nivel: 2 },
    ],
  },
  {
    bloco: "III",
    nome: "Direito Penal",
    ordem: 11,
    topicos: [
      { numero: "1", titulo: "Princípios básicos.", nivel: 1 },
      { numero: "2.2", titulo: "Lei penal no tempo.", nivel: 2 },
      { numero: "2.2.1", titulo: "Tempo do crime.", nivel: 3 },
      { numero: "2.2.2", titulo: "Conflito de leis penais no tempo.", nivel: 3 },
      { numero: "2.3", titulo: "Lei penal no espaço.", nivel: 2 },
      { numero: "2.3.1", titulo: "Lugar do crime.", nivel: 3 },
      { numero: "2.3.2", titulo: "Territorialidade.", nivel: 3 },
      { numero: "2.3.3", titulo: "Extraterritorialidade.", nivel: 3 },
      { numero: "3", titulo: "Tipicidade.", nivel: 1 },
      { numero: "3.1", titulo: "Crime doloso e crime culposo.", nivel: 2 },
      { numero: "3.2", titulo: "Erro de tipo.", nivel: 2 },
      { numero: "3.3", titulo: "Crime consumado e tentado.", nivel: 2 },
      { numero: "3.4", titulo: "Crime impossível.", nivel: 2 },
      { numero: "3.5", titulo: "Punibilidade e causas de extinção.", nivel: 2 },
      { numero: "4", titulo: "Ilicitude.", nivel: 1 },
      { numero: "4.1", titulo: "Causas de exclusão da ilicitude.", nivel: 2 },
      { numero: "4.2", titulo: "Excesso punível.", nivel: 2 },
      { numero: "5", titulo: "Culpabilidade.", nivel: 1 },
      { numero: "5.1", titulo: "Causas de exclusão da culpabilidade.", nivel: 2 },
      { numero: "5.2", titulo: "Imputabilidade.", nivel: 2 },
      { numero: "5.3", titulo: "Erro de proibição.", nivel: 2 },
      { numero: "6", titulo: "Crimes.", nivel: 1 },
      { numero: "6.1", titulo: "Crimes contra a pessoa.", nivel: 2 },
      { numero: "6.2", titulo: "Crimes contra o patrimônio.", nivel: 2 },
      { numero: "6.3", titulo: "Crimes contra a dignidade sexual.", nivel: 2 },
      { numero: "6.4", titulo: "Crimes contra a incolumidade pública.", nivel: 2 },
      { numero: "6.5", titulo: "Crimes contra a fé pública.", nivel: 2 },
      { numero: "6.6", titulo: "Crimes contra a Administração Pública.", nivel: 2 },
    ],
  },
  {
    bloco: "III",
    nome: "Direito Processual Penal",
    ordem: 12,
    topicos: [
      { numero: "1", titulo: "Ação penal.", nivel: 1 },
      { numero: "1.1", titulo: "Conceito.", nivel: 2 },
      { numero: "1.2", titulo: "Características.", nivel: 2 },
      { numero: "1.3", titulo: "Espécies.", nivel: 2 },
      { numero: "1.4", titulo: "Condições.", nivel: 2 },
      { numero: "2", titulo: "Termo Circunstanciado de Ocorrência (Lei nº 9.099/1995).", nivel: 1 },
      { numero: "2.1", titulo: "Atos processuais: forma, lugar e tempo.", nivel: 2 },
      { numero: "3", titulo: "Prova.", nivel: 1 },
      { numero: "3.1", titulo: "Conceito, objeto, classificação.", nivel: 2 },
      { numero: "3.2", titulo: "Preservação de local de crime.", nivel: 2 },
      { numero: "3.3", titulo: "Requisitos e ônus da prova.", nivel: 2 },
      { numero: "3.4", titulo: "Provas ilícitas.", nivel: 2 },
      { numero: "3.5", titulo: "Meios de prova: pericial, interrogatório, confissão, perguntas ao ofendido, testemunhas, reconhecimento de pessoas e coisas, acareação, documentos, indícios.", nivel: 2 },
      { numero: "3.6", titulo: "Busca e apreensão: pessoal, domiciliar, requisitos, restrições, horários.", nivel: 2 },
      { numero: "4", titulo: "Prisão.", nivel: 1 },
      { numero: "4.1", titulo: "Conceito, formalidades, espécies e mandado de prisão e cumprimento.", nivel: 2 },
      { numero: "4.2", titulo: "Prisão em flagrante.", nivel: 2 },
      { numero: "5", titulo: "Identificação Criminal (art. 5º, LVIII, da Constituição Federal e art. 3º da Lei nº 12.037/2009).", nivel: 1 },
      { numero: "6", titulo: "Diligências Investigatórias (art. 6º e 13 do CPP).", nivel: 1 },
    ],
  },
  {
    bloco: "III",
    nome: "Legislação Especial",
    ordem: 13,
    topicos: [
      { numero: "1", titulo: "Lei nº 5.553/1968 e Lei nº 12.037/2009.", nivel: 1 },
      { numero: "2", titulo: "Lei nº 8.069/1990 e suas alterações (ECA).", nivel: 1 },
      { numero: "3", titulo: "Lei nº 8.072/1990 e suas alterações (Crimes Hediondos).", nivel: 1 },
      { numero: "4", titulo: "Decreto nº 1.655/1995 e art. 47 do Decreto nº 9.662/2019.", nivel: 1 },
      { numero: "5", titulo: "Lei nº 9.099/1995 e suas alterações (Juizados Especiais).", nivel: 1 },
      { numero: "6", titulo: "Lei nº 9.455/1997 e suas alterações (Tortura).", nivel: 1 },
      { numero: "7", titulo: "Lei nº 9.605/1998 e suas alterações: Capítulos III e V (Crimes Ambientais).", nivel: 1 },
      { numero: "8", titulo: "Lei nº 10.826/2003 e suas alterações: Capítulo IV (Estatuto do Desarmamento).", nivel: 1 },
      { numero: "9", titulo: "Lei nº 11.343/2006 e suas alterações (Drogas).", nivel: 1 },
      { numero: "10", titulo: "Lei nº 12.850/2013 e suas alterações (Organização Criminosa).", nivel: 1 },
      { numero: "11", titulo: "Lei nº 13.675/2018 (SUSP).", nivel: 1 },
      { numero: "12", titulo: "Lei nº 13.869/2019 (Abuso de Autoridade).", nivel: 1 },
    ],
  },
  {
    bloco: "III",
    nome: "Direitos Humanos",
    ordem: 14,
    topicos: [
      { numero: "1", titulo: "Direitos humanos na Constituição Federal.", nivel: 1 },
      { numero: "1.1", titulo: "A Constituição Federal e os tratados internacionais de direitos humanos.", nivel: 2 },
      { numero: "2", titulo: "Declaração Universal dos Direitos Humanos.", nivel: 1 },
      { numero: "3", titulo: "Convenção Americana sobre Direitos Humanos (Decreto nº 678/1992).", nivel: 1 },
    ],
  },
];
